# Site settings
title: "Ethan Thibault"
tagline: "Producer and Writer"
permalink: /:collection/:title/

# Global options
hide_read_more: false

# Social
socialimg: /img/social.jpg # be sure to change this image
portrait: /img/social/portrait.jpg

# Contact
phone: "###-###-####"
email: "me@website.com"
twitter: "twitterusername"

# Font
font: '<link href="https://fonts.googleapis.com/css?family=Noto+Serif|Archivo+Black" rel="stylesheet">'
# you must use single quotes for this

# Header Nav Links
textlinks:
  "About": "/about/"
  "Interactive": "/interactive/"
  "Writing": "/writing/"

imagelinks:
  "Twitter_Logo_Blue.png": "https://twitter.com"
  "medium-m-color-100px.png": "https://medium.com"
  "In-2C-128px-TM.png": "https://linkedin.com"

# Collections
collections:
  interactive:
    output: true
    permalink: /interactive/:title/
  writing:
    permalink: /#!/
    output: false
  other:
    permalink: /#!/
    output: false

defaults:
  - scope:
      type: "interactive"
    values:
      layout: "project"

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, docs]